president_names = { 'adams': 'John Adams',
'jqadams': 'John Quincy Adams',
'arthur': 'Chester Alan Arthur',
'buchanan': 'James Buchanan',
'bush': 'George Bush',
'gwbush': 'George W. Bush',
'carter': 'Jimmy Carter',
'cleveland': 'Grover Cleveland',
'clinton': 'Bill Clinton',
'coolidge': 'Calvin Coolidge',
'eisenhower': 'Dwight D. Eisenhower',
'fillmore': 'Millard Fillmore',
'ford': 'Gerald R. Ford',
'garfield': 'James A. Garfield',
'grant': 'Ulysses S. Grant',
'harding': 'Warren G. Harding',
'bharrison': 'Benjamin Harrison',
'harrison': 'William Henry Harrison',
'hayes': 'Rutherford Birchard Hayes',
'hoover': 'Herbert Hoover',
'jackson': 'Andrew Jackson',
'jefferson': 'Thomas Jefferson',
'johnson': 'Andrew Johnson',
'lbjohnson': 'Lyndon B. Johnson',
'kennedy': 'John F. Kennedy',
'lincoln': 'Abraham Lincoln',
'madison': 'James Madison',
'mckinley': 'William McKinley',
'monroe': 'James Monroe',
'nixon': 'Richard M. Nixon',
'obama': 'Barack Obama',
'pierce': 'Franklin Pierce',
'polk': 'James K. Polk',
'reagan': 'Ronald Reagan',
'fdroosevelt': 'Franklin D. Roosevelt',
'roosevelt': 'Theodore Roosevelt',
'taft': 'William H. Taft',
'taylor': 'Zachary Taylor',
'truman': 'Harry S. Truman',
'trump': 'Donald J. Trump',
'tyler': 'John Tyler',
'vanburen': 'Martin Van Buren',
'washington': 'George Washington',
'wilson': 'Woodrow  ',
}