version: '3.4'

services:
  database:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  etl:
    depends_on: 
      - database
    image: etl
    shm_size: 2gb
    ports:
      - 8889:8889
    build: .
    volumes:
      - ..:/app
    environment:
      - DB_HOST=postgresql://postgres:postgres@database
      - DB_NAME=president_db
    command: ["jupyter", "lab", "--allow-root", "--no-browser", "--ip", "0.0.0.0" , "--port", "8889"]

volumes:
  postgres_data:
    name: etl_postgres_data