version: '3'

services:
  database:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  dataloader:
    depends_on: 
      - database
    image: dataloader
    ports:
      - 8888:8888
    build: .
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgresql://postgres:postgres@database
      - DB_NAME=president_db

volumes:
  postgres_data: