version: '3'

services:
  database:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  flask:
    depends_on: 
      - database
    image: flask
    build: .
    volumes:
      - .:/app:cached
    ports:
      - 5000:5000
      - 10001:10001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database/president_db
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DEBUG

volumes:
  postgres_data:
    external:
      name: etl_postgres_data